services:
  shopping-lists:
    build: shopping-lists
    image: shopping-lists
    restart: "no"
    volumes:
      - ./shopping-lists/:/shopping-lists
      - ./app-cache/:/app-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true" # Prevent startup on docker-compose up
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - shopping-lists
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests